-- =============================================================
-- Total customers
-- Establishes the base size of the customer base.
-- All rate and average metrics depend on this number.
SELECT
	COUNT(DISTINCT id) AS total_customers
FROM marketing_campaign;
-- Total customers: 2,240

-- =============================================================
-- Total amount spent
-- Sum of all product category spend across all customers.
-- Represents total revenue generated by this customer base.
SELECT
	SUM(mnt_wines) + SUM(mnt_fruits) + SUM(mnt_meat_products) + SUM(mnt_fish_products) + 
	SUM(mnt_sweet_products) + SUM(mnt_gold_prods) AS mnt_total
FROM marketing_campaign;
-- Total amount spent: $1,356,988

-- =============================================================
-- Total purchases
-- Sum of purchases across all channels (web, store, catalog).
-- Deals excluded — tracked separately as a behavior metric.
SELECT
	SUM(num_web_purchases) + SUM(num_catalog_purchases) + 
	SUM(num_store_purchases) AS total_purchases
FROM marketing_campaign;
-- Total purchases: 28,083


-- =============================================================
-- Purchases by channel
-- Shows where customers prefer to buy.
-- Helps the business prioritize channel investment.
SELECT
	SUM(num_web_purchases) AS total_web_purchases,
	SUM(num_catalog_purchases) AS total_catalog_purchases,
	SUM(num_store_purchases) AS total_store_purchases
FROM marketing_campaign;
-- Total purchases by channel:
-- Web: 9,150 | Catalog: 5,963 | Store: 12,970
-- FINDING: Store is the dominant purchase channel.
-- Catalog is the weakest channel — may indicate low ROI on catalog campaigns.

-- =============================================================
-- Average spend and purchases per customer
-- Core customer value metrics.
-- Baseline for segmentation — who spends above or below average?
SELECT
	ROUND((SUM(mnt_wines) + SUM(mnt_fruits) + SUM(mnt_meat_products) + SUM(mnt_fish_products) + 
	SUM(mnt_sweet_products) + SUM(mnt_gold_prods)) / COUNT(DISTINCT id)::numeric,2) AS avg_spent_by_client,
	ROUND((SUM(num_web_purchases) + SUM(num_catalog_purchases) + SUM(num_store_purchases)) 
	/ COUNT(DISTINCT id)::numeric,2) AS avg_purchase_by_client
FROM marketing_campaign;
-- Average spend per customer: $605.80
-- Average purchases per customer: 12.54
-- FINDING: Customers make roughly 12-13 purchases on average,
-- spending around $606 each — a healthy engagement level.

-- =============================================================
-- Average recency
-- Measures how recently customers made their last purchase (in days).
-- Lower values indicate more engaged, active customers.
SELECT
	ROUND(AVG(recency), 2) AS avg_recency
FROM marketing_campaign;
-- Average recency: 49.11 days
-- High recency values indicate disengaged customers worth targeting with re-engagement campaigns.

-- NOTE: True purchase frequency (purchases per time period) cannot be calculated
-- from this dataset. Average purchases per customer (12.54) is used as a proxy.

-- =============================================================
-- Overall campaign engagement rate
-- Percentage of customers who responded to at least one campaign.
-- Broad indicator of marketing reach across all campaigns.
-- Per-campaign breakdown is going to be analysed separately.
SELECT
	ROUND((SELECT COUNT(id) FROM marketing_campaign WHERE accepted_cmp1 = 1 OR accepted_cmp2 = 1 OR accepted_cmp3 = 1 OR
	accepted_cmp4 = 1 OR accepted_cmp5 = 1 OR response = 1) / COUNT(id)::numeric * 100, 2) AS percentage
FROM marketing_campaign;
-- FINDING: 27.19% of customers responded to at least one campaign.
-- Roughly 1 in 4 customers engaged with marketing efforts.
-- Over 70% were unaffected — significant room for targeting improvement.


-- =============================================================
-- Deal purchases volume and percentage
-- Measures how many purchases were made using a discount or deal.
-- Indicates the price sensitivity of the customer base.
-- High values suggest customers are heavily driven by promotions,
-- which has direct implications on margin and campaign design.
SELECT
	SUM(num_deals_purchases) AS total_deal_purchases,
	ROUND(SUM(num_deals_purchases)::numeric / (SUM(num_web_purchases) + SUM(num_catalog_purchases) + 
	SUM(num_store_purchases))::numeric * 100, 2) AS deals_purchases_percentage
FROM marketing_campaign;
-- FINDING: 5,208 deal purchases out of 28,083 total (18.55%).
-- INSIGHT: Nearly 1 in 5 purchases relies on a discount or promotion.
-- This level of deal dependency is worth monitoring — heavy reliance
-- on deals can erode margins over time.


-- =============================================================
-- Active vs inactive customers
-- Customers inactive for 90+ days are flagged as at-risk.
-- 90 days chosen as threshold based on expected quarterly engagement
-- for a business selling consumer goods across multiple categories.
-- Helps the marketing team size re-engagement campaigns.
SELECT
	(SELECT COUNT(id) FROM marketing_campaign WHERE recency < 90) AS active_customers,
	(SELECT COUNT(id) FROM marketing_campaign WHERE recency >= 90) AS inactive_customers,
	ROUND((SELECT COUNT(id) FROM marketing_campaign WHERE recency >= 90) / COUNT(id)::numeric * 100, 2) AS inactive_percentage
FROM marketing_campaign;
-- FINDING: 2,022 active customers (90.27%) vs 218 inactive (9.73%).
-- Majority of the customer base is engaged.
-- 218 customers represent a re-engagement opportunity worth prioritising.


-- =============================================================
-- High value customer profile
-- Identifies the characteristics of customers spending above
-- the average ($605.80). Helps the marketing team build targeted
-- campaigns aimed at the most valuable segment.
-- NOTE: High value defined by monetary spend only.
-- Full RFM segmentation is going to be applied later.
WITH above_average AS (
    SELECT id
    FROM marketing_campaign
	WHERE year_birth >= 1926
    GROUP BY id
    HAVING SUM(mnt_wines) + SUM(mnt_fruits) + SUM(mnt_meat_products) 
         + SUM(mnt_fish_products) + SUM(mnt_sweet_products) + SUM(mnt_gold_prods) 
         > (SELECT ROUND((SUM(mnt_wines) + SUM(mnt_fruits) + SUM(mnt_meat_products) 
            + SUM(mnt_fish_products) + SUM(mnt_sweet_products) + SUM(mnt_gold_prods)) 
            / COUNT(DISTINCT id)::numeric, 2) FROM marketing_campaign)
)

SELECT
    COUNT(mc.id) AS total_customers,
    ROUND(AVG(mc.income), 2) AS avg_income,
    ROUND(AVG(DATE_PART('year', CURRENT_DATE) - mc.year_birth)::numeric, 2) AS avg_age,
    MODE() WITHIN GROUP (ORDER BY mc.education) AS most_common_education,
    MODE() WITHIN GROUP (ORDER BY mc.marital_status) AS most_common_marital_status
FROM above_average aa
JOIN marketing_campaign mc ON aa.id = mc.id;
-- FINDING: 918 high value customers (40.98% of total base).
-- Average income: $71,004 | Average age: 59
-- Most common education: Graduation | Most common marital status: Married
-- High value customers tend to be older, married, college-educated
-- with significantly high income.

-- =============================================================
-- NOTE: Channel efficiency beyond total purchase volume cannot be calculated
-- from this dataset. Revenue and cost per channel are not available.

-- NOTE: Web conversion rate cannot be calculated accurately.
-- num_web_visits_month covers last month only while num_web_purchases
-- covers the full customer lifetime. Time windows are incomparable.