-- =============================================================
-- Total customers
-- Establishes the base size of the customer base.
-- All rate and average metrics depend on this number.
SELECT
	COUNT(DISTINCT id) AS total_customers
FROM marketing_campaign;
-- Total customers: 2,240

-- =============================================================
-- Total amount spent
-- Sum of all product category spend across all customers.
-- Represents total revenue generated by this customer base.
SELECT
	SUM(mnt_wines) + SUM(mnt_fruits) + SUM(mnt_meat_products) + SUM(mnt_fish_products) + 
	SUM(mnt_sweet_products) + SUM(mnt_gold_prods) AS mnt_total
FROM marketing_campaign;
-- Total amount spent: $1,356,988

-- =============================================================
-- Total purchases
-- Sum of purchases across all channels (web, store, catalog).
-- Deals excluded — tracked separately as a behavior metric.
SELECT
	SUM(num_web_purchases) + SUM(num_catalog_purchases) + 
	SUM(num_store_purchases) AS total_purchases
FROM marketing_campaign;
-- Total purchases: 28,083


-- =============================================================
-- Purchases by channel
-- Shows where customers prefer to buy.
-- Helps the business prioritize channel investment.
SELECT
	SUM(num_web_purchases) AS total_web_purchases,
	SUM(num_catalog_purchases) AS total_catalog_purchases,
	SUM(num_store_purchases) AS total_store_purchases
FROM marketing_campaign;
-- Total purchases by channel:
-- Web: 9,150 | Catalog: 5,963 | Store: 12,970
-- FINDING: Store is the dominant purchase channel.
-- Catalog is the weakest channel — may indicate low ROI on catalog campaigns.

-- =============================================================
-- Average spend and purchases per customer
-- Core customer value metrics.
-- Baseline for segmentation — who spends above or below average?
SELECT
	ROUND((SUM(mnt_wines) + SUM(mnt_fruits) + SUM(mnt_meat_products) + SUM(mnt_fish_products) + 
	SUM(mnt_sweet_products) + SUM(mnt_gold_prods)) / COUNT(DISTINCT id)::numeric,2) AS avg_spent_by_client,
	ROUND((SUM(num_web_purchases) + SUM(num_catalog_purchases) + SUM(num_store_purchases)) 
	/ COUNT(DISTINCT id)::numeric,2) AS avg_purchase_by_client
FROM marketing_campaign;
-- Average spend per customer: $605.80
-- Average purchases per customer: 12.54
-- FINDING: Customers make roughly 12-13 purchases on average,
-- spending around $606 each — a healthy engagement level.

-- =============================================================
-- Average recency
-- Measures how recently customers made their last purchase (in days).
-- Lower values indicate more engaged, active customers.
SELECT
	ROUND(AVG(recency), 2) AS avg_recency
FROM marketing_campaign;
-- Average recency: 49.11 days
-- High recency values indicate disengaged customers worth targeting with re-engagement campaigns.

-- NOTE: True purchase frequency (purchases per time period) cannot be calculated
-- from this dataset. Average purchases per customer (12.54) is used as a proxy.

-- =============================================================
-- Overall campaign engagement rate
-- Percentage of customers who responded to at least one campaign.
-- Broad indicator of marketing reach across all campaigns.
-- Per-campaign breakdown is going to be analysed separately.
SELECT
	ROUND((SELECT COUNT(id) FROM marketing_campaign WHERE accepted_cmp1 = 1 OR accepted_cmp2 = 1 OR accepted_cmp3 = 1 OR
	accepted_cmp4 = 1 OR accepted_cmp5 = 1 OR response = 1) / COUNT(id)::numeric * 100, 2) AS percentage
FROM marketing_campaign;
-- FINDING: 27.19% of customers responded to at least one campaign.
-- Roughly 1 in 4 customers engaged with marketing efforts.
-- Over 70% were unaffected — significant room for targeting improvement.

-- =============================================================
-- Active vs inactive customers
-- Customers inactive for 90+ days are flagged as at-risk.
-- 90 days chosen as threshold based on expected quarterly engagement
-- for a business selling consumer goods across multiple categories.
-- Helps the marketing team size re-engagement campaigns.
SELECT
	(SELECT COUNT(id) FROM marketing_campaign WHERE recency < 90) AS active_customers,
	(SELECT COUNT(id) FROM marketing_campaign WHERE recency >= 90) AS inactive_customers,
	ROUND((SELECT COUNT(id) FROM marketing_campaign WHERE recency >= 90) / COUNT(id)::numeric * 100, 2) AS inactive_percentage
FROM marketing_campaign;
-- FINDING: 2,022 active customers (90.27%) vs 218 inactive (9.73%).
-- Majority of the customer base is engaged.
-- 218 customers represent a re-engagement opportunity worth prioritising.


-- =============================================================
-- High value customer profile
-- Identifies the characteristics of customers spending above
-- the average ($605.80). Helps the marketing team build targeted
-- campaigns aimed at the most valuable segment.
-- NOTE: High value defined by monetary spend only.
-- Full RFM segmentation is going to be applied later.
WITH above_average AS (
    SELECT id
    FROM marketing_campaign
	WHERE year_birth >= 1926
    GROUP BY id
    HAVING SUM(mnt_wines) + SUM(mnt_fruits) + SUM(mnt_meat_products) 
         + SUM(mnt_fish_products) + SUM(mnt_sweet_products) + SUM(mnt_gold_prods) 
         > (SELECT ROUND((SUM(mnt_wines) + SUM(mnt_fruits) + SUM(mnt_meat_products) 
            + SUM(mnt_fish_products) + SUM(mnt_sweet_products) + SUM(mnt_gold_prods)) 
            / COUNT(DISTINCT id)::numeric, 2) FROM marketing_campaign)
)

SELECT
    COUNT(mc.id) AS total_customers,
    ROUND(AVG(mc.income), 2) AS avg_income,
    ROUND(AVG(DATE_PART('year', CURRENT_DATE) - mc.year_birth)::numeric, 2) AS avg_age,
    MODE() WITHIN GROUP (ORDER BY mc.education) AS most_common_education,
    MODE() WITHIN GROUP (ORDER BY mc.marital_status) AS most_common_marital_status
FROM above_average aa
JOIN marketing_campaign mc ON aa.id = mc.id;
-- FINDING: 918 high value customers (40.98% of total base).
-- Average income: $71,004 | Average age: 59
-- Most common education: Graduation | Most common marital status: Married
-- High value customers tend to be older, married, college-educated
-- with significantly high income.

-- =============================================================
-- NOTE: Channel efficiency beyond total purchase volume cannot be calculated
-- from this dataset. Revenue and cost per channel are not available.

-- NOTE: Web conversion rate cannot be calculated accurately.
-- num_web_visits_month covers last month only while num_web_purchases
-- covers the full customer lifetime. Time windows are incomparable.


-- =============================================================
-- Average spend by education level
-- Identifies which customer segments generate the most revenue.
-- Helps the marketing team prioritise messaging and offers
-- towards the highest value demographic groups.
SELECT
	education,
	COUNT(*) AS total_customers,
	ROUND((SUM(mnt_wines) + SUM(mnt_fruits) + SUM(mnt_meat_products) + SUM(mnt_fish_products) 
	+ SUM(mnt_sweet_products) + SUM(mnt_gold_prods)) / COUNT(1)::numeric, 2)  AS avg_amount
FROM marketing_campaign
GROUP BY education
ORDER BY 3 DESC;
-- FINDING: Spend increases broadly with education level, with one exception.
-- PhD: $672.41 (486) | Graduation: $619.90 (1,127) | Master: $611.78 (370)
-- 2n Cycle: $496.53 (203) | Basic: $81.80 (54)
-- INSIGHT: Graduation is the largest and second highest spending segment —
-- the most strategically valuable group by volume and total revenue.
-- Master spends slightly less than Graduation despite higher education level,
-- likely due to sample composition rather than a true spending pattern.
-- Basic education customers spend 88% less than PhD customers.

-- =============================================================
-- Age distribution overview
-- Establishes the age range and average age of the customer base.
-- Used to define meaningful age brackets for segmentation.
SELECT
    MIN(DATE_PART('year', CURRENT_DATE) - year_birth) AS min_age,
    MAX(DATE_PART('year', CURRENT_DATE) - year_birth) AS max_age,
     ROUND(AVG(DATE_PART('year', CURRENT_DATE) - year_birth)::numeric, 1) AS avg_age
FROM marketing_campaign
WHERE year_birth >= 1926;
-- FINDING: Age range: 30–86 | Average age: 57
-- Customer base skews older — majority above 50.
-- 3 records excluded (year_birth before 1926) as likely erroneous entries.

-- =============================================================
-- Average spend and number of customers by age group
-- Segments customers into standard marketing age brackets.
-- Reveals which life stage generates the most revenue.
SELECT
	CASE 
		WHEN DATE_PART('year', CURRENT_DATE) - year_birth >= 30 AND DATE_PART('year', CURRENT_DATE) - year_birth < 40
		THEN 'Young Adults'
		WHEN DATE_PART('year', CURRENT_DATE) - year_birth >= 40 AND DATE_PART('year', CURRENT_DATE) - year_birth < 50
		THEN 'Middle Age'
		WHEN DATE_PART('year', CURRENT_DATE) - year_birth >= 50 AND DATE_PART('year', CURRENT_DATE) - year_birth < 60
		THEN 'Mature'
		WHEN DATE_PART('year', CURRENT_DATE) - year_birth >= 60 AND DATE_PART('year', CURRENT_DATE) - year_birth < 70
		THEN 'Senior'
		ELSE 'Elder'
	END AS age_group,
	COUNT(id) AS total_customers,
	ROUND((SUM(mnt_wines) + SUM(mnt_fruits) + SUM(mnt_meat_products) + SUM(mnt_fish_products) 
	+ SUM(mnt_sweet_products) + SUM(mnt_gold_prods)) / COUNT(id)::numeric, 2)  AS avg_amount
FROM marketing_campaign
WHERE year_birth >= 1926
GROUP BY 1
ORDER BY 3 DESC;
-- FINDING: Elder (70–86): $735.55 (420) | Young Adults (30–39): $686.91 (147)
-- Senior (60–69): $657.38 (487) | Mature (50–59): $545.77 (724) | Middle Age (40–49): $500.79 (459)
-- INSIGHT: Elder customers are the highest spenders despite not being the largest group —
-- likely due to higher disposable income post-retirement.
-- Middle Age customers spend the least, consistent with peak family financial obligations.
-- Mature is the largest segment (724) and represents the core customer base.